language: csharp
sudo: required  
dist: xenial  
mono: latest
env:
  global:
    - ResolveNuGetPackageAssets=true
    - EnableNuGetPackageRestore=true
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
os:
  - linux
  - osx
solution: Afonsoft.EFCore.sln
install:
  - nuget restore Afonsoft.EFCore.sln
script:
  - xbuild /p:Configuration=Release Afonsoft.EFCore.sln